# Generated by Django 4.2.3 on 2025-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('education_level', models.JSONField()),
                ('experience', models.CharField(max_length=500)),
                ('career_preferences', models.CharField(max_length=255)),
            ],
        ),
    ]
