# Generated by Django 5.1.7 on 2025-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_userprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('career_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('required_skills', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
